#!/usr/bin/env bash
folder="//home/potato/Desktop/PMMode/PMMode-Test"
bochsFolder="/home/potato/Desktop/Bochs Folder"
cd "$folder"
nasm -f bin boot.asm -l boot.lst
sudo dd if=boot of="$bochsFolder/test.iso" bs=512 count=1
sudo chmod u=rwx,g=rwx,o=rwx "$bochsFolder/test.iso"
cd "$bochsFolder"
bochs
$SHELL

